[package]
name = "tissue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tao = "0.25"
wry = "0.37"
num-traits = "0.2.15"
